analytics.integration.enable=true
analytics.onpremise.enable=false
analytics.project={"id"\:3449369,"name"\:"Sample - HR Web App \#3449369","teamId"\:3425938,"status"\:null,"gitRepositories"\:null,"team"\:null,"organizationId"\:3480330,"accountId"\:null,"sampleProject"\:false,"autoIntegrate"\:false}
analytics.team={"id"\:3425938,"role"\:null,"name"\:null,"organization"\:null}
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
